### ISSUE TITLE
should the reserved characters be an array of characters instead?

### ISSUE THREAD

**Issue by baywet** [andreaTP/std-uritemplate#1]
https://github.com/andreaTP/std-uritemplate/blob/186c831965511594db1adf75532d7af74ff6018b/java/src/main/java/org/uritemplate/StdUriTemplate.java#L288

**Comment by andreaTP** [comment]
Unfortunately, the `String` class in Java exposes a `contains` method that only takes String as an argument and not characters ...
All of the alternatives using plain characters are involving RegExp, which I carefully attempted to avoid in this implementation.

**Comment by andreaTP** [comment]
That said, I'm completely open to a more performant validation mechanism! (at the moment is "kind of" added on top and is not integrated with the processing loops).

**Comment by andreaTP** [comment]
I'll take this comment into consideration while stabilizing the implementation and ask some experts to review the performance.
When I'll port the implementation to C# I'll definitely use `OrdinalIgnoreCase` for comparisons, thanks for the tip!

**Comment by andreaTP** [comment]
Closed with #10
