### ISSUE TITLE
while this is a very clean implementation, wouldn't it result in a lot of allocs because of classes use?

### ISSUE THREAD

**Issue by baywet** [andreaTP/std-uritemplate#2]
https://github.com/andreaTP/std-uritemplate/blob/186c831965511594db1adf75532d7af74ff6018b/java/src/main/java/org/uritemplate/StdUriTemplate.java#L374

**Comment by andreaTP** [comment]
At the moment we are allocating, for each expansion block (`{...}`):
 - 1 object for the Modifier
 - 1 object for each Token
 
I was assuming that the runtime(at least the JVM) should be smart enough to inline everything, but I'll double-check with some performance experts.

**Comment by andreaTP** [comment]
Closed with #10
